apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-mirrord-demo-main-service
  labels:
    app: ls-mirrord-demo-main-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ls-mirrord-demo-main-service
  template:
    metadata:
      labels:
        app: ls-mirrord-demo-main-service
    spec:
      containers:
      - name: ls-mirrord-demo-main-service
        image: 000000000000.dkr.ecr.us-east-1.localhost.localstack.cloud:4566/localstack-mirrord-demo
        command: [python]
        args: ["/app/services/main-service/service.py"]
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector:
    app: ls-mirrord-demo-main-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /main
            pathType: Prefix
            backend:
              service:
                name: main-service
                port:
                  number: 80
